### ISSUE TITLE
DCS will not load liberation aircraft after recent DCS update

### ISSUE THREAD

**Issue by skycoog** [dcs-liberation/dcs_liberation#3421]
### Affected versions

11.1.1

### Build information

DCS Liberation 11.1.1

### Description

I'm using a Fox dedicated server for Liberation.  When I log onto the server after the update, it asks me to pick a blue or red coalition side.  My aircraft is listed in the blue coalition side, I can pick it, but after the briefing it will not load me into the aircraft.  When I cycle through to the aircraft carrier in observer mode, it does not appear that any of the F18's or missions are spawning.  I'm using t he Syria map.

### Save game and other files (save game required, bugs without saves will be closed)

[syria3liberation.liberation.zip](https://github.com/user-attachments/files/16199261/syria3liberation.liberation.zip)

**Comment by dexpilot** [comment]
Same problem with me.

**Comment by skycoog** [comment]
Hey Dex,

I was able to overcome the problem using a hack provided by another user.
If you open the mission up in the mission editor, make no changes, and then
save, it will work.

Best of luck,

Sky

**Comment by zhexu14** [comment]
This issue is now fixed for 2.9.6 (and tested in 2.9.7) in the development build (#3431 )

**Comment by Mintox99** [comment]
Nope I can confirm this isnt fixed. Aircraft are not spawning still.

**Comment by Starfire13** [comment]
> Nope I can confirm this isnt fixed. Aircraft are not spawning still. 

Are you using the correct dev build?

**Comment by suempu** [comment]
bug still exists. also in 12.0.1. hope you fix this soon. makes it unusable for navy planes
