### ISSUE TITLE
OSError: invalid face handle

### ISSUE THREAD

**Issue by shomke** [dcs-liberation/dcs_liberation#531]
All releases from version 2.1.1 give me the ''OSError: invalid face handle error'' (sometimes a direct crash) on clicking the Take Off button. Version 2.1.0 and previous versions work fine.
Issue related with kneeboards?
Clean reinstallation of DCS doesn't solve the issue.

![Capture](https://user-images.githubusercontent.com/75780016/101748250-9ad01680-3acc-11eb-96db-e2940df63f0d.PNG)

**Comment by DanAlbert** [comment]
https://github.com/python-pillow/Pillow/issues/3066 hints that this might be fixed by updating to the (not yet released, I think) new version of pillow. That seems to be related to non-ascii text though, which I don't think we'd be printing to the kneeboard.

**Comment by Khopa** [comment]
What is your system language/locale ? 

@DanAlbert Maybe this could happen if a font is not installed too ?

**Comment by shomke** [comment]
Win10 Pro, in English. Based in Norway.

**Comment by DanAlbert** [comment]
We ship the fized-width font we use, but do rely on the system having Arial. If there's something odd about the Arial on your system that could explain it. We ought to be shipping all our fonts regardless though.

**Comment by shomke** [comment]
![Capture](https://user-images.githubusercontent.com/75780016/101935121-d9ee8c80-3bde-11eb-8c79-8cf42b7826aa.PNG)
Those are the fonts I have installed on my system. Any additional font I could install manually to test out?

**Comment by shomke** [comment]
Hi again. I have been testing again, with puzzling results.
Here is the measured outcome when clicking the Take Off button.

Direct crash - c.a. 60%
''OSError: invalid face handle error'' message - c.a. 30%
Works fine, mission popup ok - c.a. 10%

So I manage to play. Just take a bit of effort before I eventually avoid the crash...
Puzzling because it looks random.

**Comment by walterroach** [comment]
Report from Discord user Hanne:

It seems that I fixed the bug - at least 5/5 attempts just worked. I took a look at kneeboard.py, discovered the "Inconsolata.otf" used and then installed it from the fonts folder. Since then, the familiar mission start screen comes up and the comando line is clean.

**Comment by shomke** [comment]
I installed manually the Inconsolata.otf font yesterday, but the bug is still here for me.

**Comment by Hanninho** [comment]
I looked into the bug again and discovered the following hint: https://github.com/python-pillow/Pillow/issues/3066#issuecomment-643661625

Accordingly, I modified the fonts of the KneeboardPageWriter:
```
        self.title_font = ImageFont.truetype("arial.ttf", 32, layout_engine=ImageFont.LAYOUT_BASIC)
        self.heading_font = ImageFont.truetype("arial.ttf", 24, layout_engine=ImageFont.LAYOUT_BASIC)
        self.content_font = ImageFont.truetype("arial.ttf", 20, layout_engine=ImageFont.LAYOUT_BASIC)
        self.table_font = ImageFont.truetype("resources/fonts/Inconsolata.otf", 20, layout_engine=ImageFont.LAYOUT_BASIC)
```

I'm more cautious with my predictions now, but I have been able to generate different missions so far.

**Comment by shomke** [comment]
I don't really know how to test it, I doesn't manage to run Liberation from the source so far.
I hope that the fix solves the error and can be pushed :)

**Comment by DanAlbert** [comment]
Fix seems plausible. If someone experiencing this bug could verify the build from https://github.com/Khopa/dcs_liberation/actions/runs/736833008 we'll merge.

**Comment by DanAlbert** [comment]
Thanks @Hanninho for the fix. I've merged to 2.5 and also cherry-picked to 2.4 in case we end up doing a 2.4.4, which seems likely.

**Comment by shomke** [comment]
I confirm that the fix works! Thanks for it.
