### ISSUE TITLE
replace TAKE-OFF button with GENERATE + COMMIT

### ISSUE THREAD

**Issue by HILOK** [dcs-liberation/dcs_liberation#831]
**Is your feature request related to a problem? Please describe.**
after hitting the TAKE-OFF button, i like to refine my missions (fine-tune routing, use dynamic weather) in DCS's ME, as well as taking note of some information from the ME that i dont necessarily find in liberation's planner, e.g. detailed weather, bullseye, callsigns of escort etc.
if i dont play the mission after doing so, those changes are lost, the next time i launch liberation and hit TAKE-OFF.

**Describe the solution you'd like**
i would like to suggest a GENERATE button that only generates the liberation_next.miz file, and a separate COMMIT button, when the player is ready to actually play the mission.

**Comment by DanAlbert** [comment]
> if i dont play the mission after doing so, those changes are lost, the next time i launch liberation and hit TAKE-OFF.

Already fixed in 2.4. There is no separate process for two buttons here. Generation was the thing that caused the problem.

**Comment by HILOK** [comment]
it's actually still an issue in 2.4: clicking on take-off in the GUI will overwrite the liberation_next.miz every time.
any chance this could be resolved? thanks

**Comment by DanAlbert** [comment]
Oh, I'd misunderstood this to be about the non-determinism of mission generation in 2.3.

**Comment by DanAlbert** [comment]
You don't need these buttons, by the way. Loading your mission in DCS before clicking take off has the same effect.

**Comment by HILOK** [comment]
> Oh, I'd misunderstood this to be about the non-determinism of mission generation in 2.3.

ah i see : ) 

> You don't need these buttons, by the way. Loading your mission in DCS before clicking take off has the same effect.

good to know. i'll try this as a workaround, thanks.

**Comment by Mustang-25** [comment]
I believe all the issues in this request have been resolved. Closing it out but it can be reopened if I missed something.
